
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async takePendingOpenPaths() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_pending_open_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(newSettings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { newSettings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordTelemetryEvent(event: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_telemetry_event", { event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecents() : Promise<Result<RecentEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePinRecent(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pin_recent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkRecovery() : Promise<Result<RecoveredDoc[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_recovery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNewDocument(mode: string, title: string) : Promise<Result<OpenedDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_document", { mode, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDocument(path: string) : Promise<Result<OpenedDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecoveredDocument(path: string) : Promise<Result<OpenedDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recovered_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardRecoverySnapshots() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_recovery_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markCleanShutdown() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_clean_shutdown") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDocument(path: string, mode: string, title: string, bodyJson: string, documentId: string | null) : Promise<Result<RedocMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_document", { path, mode, title, bodyJson, documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async autosaveDocument(docId: string, mode: string, title: string, bodyJson: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("autosave_document", { docId, mode, title, bodyJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDocument(mode: string, format: string, bodyJson: string, title: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_document", { mode, format, bodyJson, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectExportCompatibility(mode: string, format: string, bodyJson: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_export_compatibility", { mode, format, bodyJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async applyExportFixups(mode: string, format: string, bodyJson: string) : Promise<Result<ExportFixupResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("apply_export_fixups", { mode, format, bodyJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDocumentToFile(path: string, mode: string, format: string, bodyJson: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_document_to_file", { path, mode, format, bodyJson, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async computeDocWordCount(docJsonStr: string) : Promise<Result<DocWordCount, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_doc_word_count", { docJsonStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchDocText(docJsonStr: string, query: string, caseSensitive: boolean) : Promise<Result<SearchMatch[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_doc_text", { docJsonStr, query, caseSensitive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSheetCsvCmd(sheetData: SheetData) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_sheet_csv_cmd", { sheetData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportCsvToFile(path: string, sheetData: SheetData) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_csv_to_file", { path, sheetData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCsvFile(path: string) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCsvFileWithOptions(path: string, delimiter: string | null, encoding: string) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv_file_with_options", { path, delimiter, encoding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importXlsxFile(path: string) : Promise<Result<XlsxImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_xlsx_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDocxFile(path: string) : Promise<Result<DocxImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_docx_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importPptxFile(path: string) : Promise<Result<PptxImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_pptx_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recalculateWorkbook(workbook: WorkbookModel) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recalculate_workbook", { workbook }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkbookCellValue(workbook: WorkbookModel, sheetIdx: number, row: number, col: number, rawValue: string) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workbook_cell_value", { workbook, sheetIdx, row, col, rawValue }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fillWorkbookSeries(workbook: WorkbookModel, sheetIdx: number, sourceRow: number, sourceCol: number, targetRow: number, targetCol: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fill_workbook_series", { workbook, sheetIdx, sourceRow, sourceCol, targetRow, targetCol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sortWorkbookRange(workbook: WorkbookModel, sheetIdx: number, range: CellRange, sortCol: number, ascending: boolean) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sort_workbook_range", { workbook, sheetIdx, range, sortCol, ascending }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sortWorkbookRangeMulti(workbook: WorkbookModel, sheetIdx: number, range: CellRange, keys: ([number, boolean])[]) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sort_workbook_range_multi", { workbook, sheetIdx, range, keys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPresenterWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_presenter_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async presenterNav(slideIndex: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("presenter_nav", { slideIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertRowsCmd(workbook: WorkbookModel, sheetIdx: number, atRow: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_rows_cmd", { workbook, sheetIdx, atRow, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRowsCmd(workbook: WorkbookModel, sheetIdx: number, atRow: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rows_cmd", { workbook, sheetIdx, atRow, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertColsCmd(workbook: WorkbookModel, sheetIdx: number, atCol: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_cols_cmd", { workbook, sheetIdx, atCol, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteColsCmd(workbook: WorkbookModel, sheetIdx: number, atCol: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cols_cmd", { workbook, sheetIdx, atCol, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFreezeCmd(workbook: WorkbookModel, sheetIdx: number, freezeRows: number, freezeCols: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_freeze_cmd", { workbook, sheetIdx, freezeRows, freezeCols }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logFrontendError(level: string, message: string, stack: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend_error", { level, message, stack }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pathsExist(paths: string[]) : Promise<boolean[]> {
    return await TAURI_INVOKE("paths_exist", { paths });
},
async presenterSync(payload: PresenterSyncPayload) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("presenter_sync", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Version-history drawer source: rotated autosave snapshots for a doc id.
 */
async listDocumentHistory(docId: string) : Promise<Result<HistoryEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("list_document_history", { docId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Last-write-wins comparison between two on-disk `.redoc` files.
 * Used by the merge prompt: the newer revision wins, and equal revisions
 * with different hashes surface both sides via `compare.ts` instead of
 * silently overwriting.
 */
async compareDocumentFiles(currentPath: string, candidatePath: string) : Promise<Result<MergeDecision, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compare_document_files", { currentPath, candidatePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { theme: string; autosaveIntervalMs: number; spellcheckEnabled: boolean; fontSizeDefault: number; telemetryEnabled: boolean; zoomLevel?: number; checkForUpdates?: boolean; author?: AuthorProfile }
export type ArraySpill = { originRow: number; originCol: number; rows: number; cols: number; values: string[] }
export type AssetInfo = { hash: string; mime: string; name: string; size: number }
/**
 * Local-first author identity stored in app settings.
 * 
 * Replaces ad-hoc `author: None` / hardcoded `"You"` / `"Owner: me"`
 * fallbacks: editors resolve the display name from here and only fall
 * back to `"You"` for older documents that predate the profile.
 */
export type AuthorProfile = { displayName: string; email: string | null; color?: string | null }
export type AutoFilterState = { enabled: boolean; startRow: number; endRow: number; startCol: number; endCol: number; 
/**
 * Per-column selected values (empty = show all). Key = column index.
 */
columnFilters: { [key in number]: string[] } }
export type BorderEdge = { 
/**
 * Bounded Excel-compatible border line styles.
 */
style: string; color?: string | null }
/**
 * Per-side border definition shared by the editor, model, and XLSX round-trip.
 */
export type CellBorders = { top?: BorderEdge | null; right?: BorderEdge | null; bottom?: BorderEdge | null; left?: BorderEdge | null }
export type CellCommentModel = { id: string; row: number; col: number; author: string; text: string; resolved?: boolean; createdAt?: string }
export type CellRange = { startRow: number; endRow: number; startCol: number; endCol: number }
export type CellStyle = { bold: boolean | null; italic: boolean | null; underline: boolean | null; fontColor: string | null; bgColor: string | null; align: string | null; format: string | null; wrap?: boolean | null; vAlign?: string | null; validation?: ListValidation | null; hyperlink?: string | null; 
/**
 * Optional bounded inline image associated with this cell in Redoc.
 * PNG/JPEG values can round-trip through native XLSX drawings.
 */
image?: string | null; 
/**
 * Font family name; survives .redoc saves and XLSX export. Older files
 * deserialize without it (serde default).
 */
fontFamily?: string | null; 
/**
 * Font size in points.
 */
fontSize?: number | null; 
/**
 * Digits after the decimal point for numeric display (0-10).
 */
decimals?: number | null; 
/**
 * Per-side cell borders; round-trips through native XLSX border styles.
 */
borders?: CellBorders | null }
export type ChartModel = { chartType: string; title?: string | null; startRow: number; endRow: number; startCol: number; endCol: number }
export type ConditionalFormattingRange = { startRow: number; endRow: number; startCol: number; endCol: number }
export type ConditionalFormattingRule = { range: ConditionalFormattingRange; type: string; value?: string | null; value2?: string | null; style?: ConditionalFormattingStyle | null; scaleColors?: string[] }
export type ConditionalFormattingStyle = { fontColor?: string | null; bgColor?: string | null; bold?: boolean | null; italic?: boolean | null }
export type DeckModel = { slides: Slide[]; theme: SlideTheme; canvasWidth: number; canvasHeight: number; activeSlideIndex: number; fadeBetweenSlides?: boolean }
export type DocWordCount = { words: number; characters: number; paragraphs: number }
export type DocxImportResponse = { document: any; warnings: string[] }
export type ElementKind = { Text: { text: string; fontSize: number; fontFamily: string; color: string; align: string; bold?: boolean; italic?: boolean; underline?: boolean; bullets?: boolean } } | { Shape: { shapeType: string; fillColor: string; strokeColor: string; strokeWidth: number; text?: string; fillGradient?: ShapeGradient | null; shadow?: boolean; fontFamily?: string | null; bold?: boolean; italic?: boolean; underline?: boolean } } | { Image: { assetHash: string; mime: string } } | { Table: { rows: number; cols: number; data: string[][]; 
/**
 * Merged ranges anchored at (row, col) with row/col spans.
 */
merges: TableMerge[]; headerRow?: boolean; tableStyle?: string | null } } | { Chart: { chartType: string; data: number[]; labels: string[]; legend?: boolean; showLabels?: boolean; showAxes?: boolean } }
export type ExportFixupResponse = { body: any; applied: string[]; warnings: string[] }
/**
 * One entry in the local-first version history: a rotated `.bak*`
 * snapshot plus the attribution captured in its container meta.
 */
export type HistoryEntry = { slot: string; path: string; title: string; author: string | null; lastModifiedBy: string | null; updatedAt: number; revision: number; bodyHash: string }
export type ListValidation = { type: string; options: string[]; formula?: string | null }
/**
 * Last-write-wins comparison between the on-disk file and a snapshot.
 */
export type MergeDecision = { winner: string; currentRevision: number; candidateRevision: number; currentHash: string; candidateHash: string; changed: boolean }
export type MergeRange = { startRow: number; endRow: number; startCol: number; endCol: number }
export type NamedRange = { name: string; rangeStr: string; sheet: string | null }
export type OpenedDocument = { meta: RedocMeta; body: any }
export type PivotTableModel = { id: string; sourceRange: CellRange; rowField: number; 
/**
 * When set, the pivot crosses rows × this column field (multi-field).
 */
columnField?: number | null; valueField: number; aggregation: string; outputStartRow: number; outputStartCol: number; outputRowCount?: number | null; outputColCount?: number | null }
export type PptxImportResponse = { deck: DeckModel; warnings: string[] }
export type PresenterSyncPayload = { slide_index: number; deck_version: number; elapsed_ms: number; is_playing: boolean }
export type RecentEntry = { id: string; path: string; title: string; mode: string; lastOpenedAt: number; pinned: boolean }
export type RecoveredDoc = { id: string; title: string; mode: string; path: string | null; snapshotPath: string; timestamp: number }
export type RedocMeta = { formatVersion: number; id: string; mode: string; title: string; createdAt: number; updatedAt: number; author: string | null; 
/**
 * Bounded list of collaborator display names that edited this file
 * on this device (local-first attribution, no server account).
 */
collaborators?: string[]; 
/**
 * Last-writer-wins marker: unix seconds + author of the winning write.
 * Readers use it for the merge prompt / history drawer ordering.
 */
revision?: number; lastModifiedBy?: string | null; 
/**
 * Simple per-document capability list, e.g. `["read","comment"]`
 * (absence of `"write"` renders the document read-only in the shell).
 */
permissions?: string[]; appVersion: string; assets: AssetInfo[]; dirtyOnCrash: boolean | null; readOnly?: boolean | null; warning?: string | null }
export type ScenarioCellChange = { row: number; col: number; rawValue: string }
export type ScenarioModel = { id: string; name: string; changes: ScenarioCellChange[] }
export type SearchMatch = { text: string; index: number; lineNumber: number }
/**
 * Bounded linear-gradient fill for closed shapes.
 */
export type ShapeGradient = { from: string; to: string; angle?: number }
export type SheetCell = { rawValue: string; displayValue: string; formula: string | null; style: CellStyle | null }
export type SheetData = { id: string; name: string; cells: { [key in string]: SheetCell }; colWidths: { [key in number]: number }; rowHeights: { [key in number]: number }; freezeRows: number; freezeCols: number; charts?: ChartModel[]; filterQuery?: string | null; merges?: MergeRange[]; autoFilter?: AutoFilterState | null; conditionalFormatting?: ConditionalFormattingRule[]; pivotTables?: PivotTableModel[]; tables?: TableModel[]; scenarios?: ScenarioModel[]; slicers?: SlicerModel[]; 
/**
 * Bounded materialized results for dynamic-array formulas. The origin
 * remains the only editable formula cell; values are render metadata.
 */
spills?: ArraySpill[]; 
/**
 * Cell-anchored review comments (offline collaboration affordance).
 */
comments?: CellCommentModel[] }
export type SlicerModel = { id: string; title: string; sourceRange: CellRange; column: number; selectedValues?: string[] }
export type Slide = { id: string; layout: string; elements: SlideElement[]; notes: string; bgOverride: string | null; 
/**
 * Per-slide transition: "none" | "fade" | "slide-left" | "slide-right"
 * | "wipe-left" | "wipe-right" | "zoom" | "dissolve"
 */
transition?: string; 
/**
 * Slide-anchored review comments (offline collaboration affordance).
 */
comments?: SlideCommentModel[] }
export type SlideCommentModel = { id: string; author: string; text: string; resolved?: boolean; createdAt?: string }
export type SlideElement = { id: string; x: number; y: number; width: number; height: number; rotation: number; zIndex: number; 
/**
 * Per-element entrance animation: "none" | "fade" | "zoom"
 */
entrance?: string; 
/**
 * Optional timing metadata for the supported entrance-animation subset.
 * Keeping these fields optional preserves older `.redoc` documents and
 * avoids serializing defaults when no animation is configured.
 */
entranceDelayMs?: number | null; entranceDurationMs?: number | null; entranceOrder?: number | null; 
/**
 * Per-element exit animation: "none" | "fade". Played when the slide is
 * left in presenter view; persisted alongside the entrance metadata.
 */
exit?: string; exitDurationMs?: number | null; 
/**
 * Optional safe hyperlink target attached to the whole element.
 * 
 * The editor accepts bounded http(s), mailto, and tel targets. PPTX
 * export emits these as external relationship-backed hyperlinks; older
 * Redoc documents omit this field and continue to deserialize cleanly.
 */
hyperlink?: string | null; kind: ElementKind }
export type SlideTheme = { id: string; name: string; bgColor: string; textColor: string; accentColor: string; fontFamily: string }
/**
 * Merged table range anchored at (row, col).
 */
export type TableMerge = { r: number; c: number; rowspan: number; colspan: number }
export type TableModel = { id: string; name: string; range: CellRange; columns?: string[]; style?: string | null; showHeaderRow?: boolean; showTotalRow?: boolean }
export type WorkbookModel = { sheets: SheetData[]; activeSheetIndex: number; namedRanges?: NamedRange[] }
export type XlsxImportResponse = { workbook: WorkbookModel; warnings: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
