
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async takePendingOpenPaths() : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("take_pending_open_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getSettings() : Promise<Result<AppSettings, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_settings") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateSettings(newSettings: AppSettings) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_settings", { newSettings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recordTelemetryEvent(event: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("record_telemetry_event", { event }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getRecents() : Promise<Result<RecentEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_recents") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async togglePinRecent(id: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_pin_recent", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async checkRecovery() : Promise<Result<RecoveredDoc[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("check_recovery") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createNewDocument(mode: string, title: string) : Promise<Result<OpenedDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_new_document", { mode, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDocument(path: string) : Promise<Result<OpenedDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openRecoveredDocument(path: string) : Promise<Result<OpenedDocument, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_recovered_document", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discardRecoverySnapshots() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discard_recovery_snapshots") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async markCleanShutdown() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mark_clean_shutdown") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveDocument(path: string, mode: string, title: string, bodyJson: string, documentId: string | null) : Promise<Result<RedocMeta, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_document", { path, mode, title, bodyJson, documentId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async autosaveDocument(docId: string, mode: string, title: string, bodyJson: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("autosave_document", { docId, mode, title, bodyJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDocument(mode: string, format: string, bodyJson: string, title: string) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_document", { mode, format, bodyJson, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async inspectExportCompatibility(mode: string, format: string, bodyJson: string) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("inspect_export_compatibility", { mode, format, bodyJson }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportDocumentToFile(path: string, mode: string, format: string, bodyJson: string, title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_document_to_file", { path, mode, format, bodyJson, title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async computeDocWordCount(docJsonStr: string) : Promise<Result<DocWordCount, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("compute_doc_word_count", { docJsonStr }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async searchDocText(docJsonStr: string, query: string, caseSensitive: boolean) : Promise<Result<SearchMatch[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("search_doc_text", { docJsonStr, query, caseSensitive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportSheetCsvCmd(sheetData: SheetData) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_sheet_csv_cmd", { sheetData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async exportCsvToFile(path: string, sheetData: SheetData) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("export_csv_to_file", { path, sheetData }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCsvFile(path: string) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importCsvFileWithOptions(path: string, delimiter: string | null, encoding: string) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_csv_file_with_options", { path, delimiter, encoding }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importXlsxFile(path: string) : Promise<Result<XlsxImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_xlsx_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importDocxFile(path: string) : Promise<Result<DocxImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_docx_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async importPptxFile(path: string) : Promise<Result<PptxImportResponse, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("import_pptx_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async recalculateWorkbook(workbook: WorkbookModel) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("recalculate_workbook", { workbook }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWorkbookCellValue(workbook: WorkbookModel, sheetIdx: number, row: number, col: number, rawValue: string) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_workbook_cell_value", { workbook, sheetIdx, row, col, rawValue }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fillWorkbookSeries(workbook: WorkbookModel, sheetIdx: number, sourceRow: number, sourceCol: number, targetRow: number, targetCol: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fill_workbook_series", { workbook, sheetIdx, sourceRow, sourceCol, targetRow, targetCol }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sortWorkbookRange(workbook: WorkbookModel, sheetIdx: number, range: CellRange, sortCol: number, ascending: boolean) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sort_workbook_range", { workbook, sheetIdx, range, sortCol, ascending }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async sortWorkbookRangeMulti(workbook: WorkbookModel, sheetIdx: number, range: CellRange, keys: ([number, boolean])[]) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("sort_workbook_range_multi", { workbook, sheetIdx, range, keys }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openPresenterWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_presenter_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async presenterNav(slideIndex: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("presenter_nav", { slideIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openLogsFolder() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_logs_folder") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertRowsCmd(workbook: WorkbookModel, sheetIdx: number, atRow: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_rows_cmd", { workbook, sheetIdx, atRow, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteRowsCmd(workbook: WorkbookModel, sheetIdx: number, atRow: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_rows_cmd", { workbook, sheetIdx, atRow, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async insertColsCmd(workbook: WorkbookModel, sheetIdx: number, atCol: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("insert_cols_cmd", { workbook, sheetIdx, atCol, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async deleteColsCmd(workbook: WorkbookModel, sheetIdx: number, atCol: number, count: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_cols_cmd", { workbook, sheetIdx, atCol, count }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFreezeCmd(workbook: WorkbookModel, sheetIdx: number, freezeRows: number, freezeCols: number) : Promise<Result<WorkbookModel, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_freeze_cmd", { workbook, sheetIdx, freezeRows, freezeCols }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async logFrontendError(level: string, message: string, stack: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_frontend_error", { level, message, stack }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pathsExist(paths: string[]) : Promise<boolean[]> {
    return await TAURI_INVOKE("paths_exist", { paths });
},
async presenterSync(payload: PresenterSyncPayload) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("presenter_sync", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AppSettings = { theme: string; autosaveIntervalMs: number; spellcheckEnabled: boolean; fontSizeDefault: number; telemetryEnabled: boolean; zoomLevel?: number; checkForUpdates?: boolean }
export type AssetInfo = { hash: string; mime: string; name: string; size: number }
export type AutoFilterState = { enabled: boolean; startRow: number; endRow: number; startCol: number; endCol: number; 
/**
 * Per-column selected values (empty = show all). Key = column index.
 */
columnFilters: { [key in number]: string[] } }
export type CellRange = { startRow: number; endRow: number; startCol: number; endCol: number }
export type CellStyle = { bold: boolean | null; italic: boolean | null; underline: boolean | null; fontColor: string | null; bgColor: string | null; align: string | null; format: string | null; wrap?: boolean | null; vAlign?: string | null; validation?: ListValidation | null; hyperlink?: string | null }
export type ChartModel = { chartType: string; title?: string | null; startRow: number; endRow: number; startCol: number; endCol: number }
export type ConditionalFormattingRange = { startRow: number; endRow: number; startCol: number; endCol: number }
export type ConditionalFormattingRule = { range: ConditionalFormattingRange; type: string; value?: string | null; value2?: string | null; style?: ConditionalFormattingStyle | null; scaleColors?: string[] }
export type ConditionalFormattingStyle = { fontColor?: string | null; bgColor?: string | null; bold?: boolean | null; italic?: boolean | null }
export type DeckModel = { slides: Slide[]; theme: SlideTheme; canvasWidth: number; canvasHeight: number; activeSlideIndex: number; fadeBetweenSlides?: boolean }
export type DocWordCount = { words: number; characters: number; paragraphs: number }
export type DocxImportResponse = { document: any; warnings: string[] }
export type ElementKind = { Text: { text: string; fontSize: number; fontFamily: string; color: string; align: string; bold?: boolean; italic?: boolean; underline?: boolean; bullets?: boolean } } | { Shape: { shapeType: string; fillColor: string; strokeColor: string; strokeWidth: number; text?: string } } | { Image: { assetHash: string; mime: string } } | { Table: { rows: number; cols: number; data: string[][] } } | { Chart: { chartType: string; data: number[]; labels: string[] } }
export type ListValidation = { type: string; options: string[] }
export type MergeRange = { startRow: number; endRow: number; startCol: number; endCol: number }
export type NamedRange = { name: string; rangeStr: string; sheet: string | null }
export type OpenedDocument = { meta: RedocMeta; body: any }
export type PivotTableModel = { id: string; sourceRange: CellRange; rowField: number; valueField: number; aggregation: string; outputStartRow: number; outputStartCol: number; outputRowCount?: number | null }
export type PptxImportResponse = { deck: DeckModel; warnings: string[] }
export type PresenterSyncPayload = { slide_index: number; deck_version: number; elapsed_ms: number; is_playing: boolean }
export type RecentEntry = { id: string; path: string; title: string; mode: string; lastOpenedAt: number; pinned: boolean }
export type RecoveredDoc = { id: string; title: string; mode: string; path: string | null; snapshotPath: string; timestamp: number }
export type RedocMeta = { formatVersion: number; id: string; mode: string; title: string; createdAt: number; updatedAt: number; author: string | null; appVersion: string; assets: AssetInfo[]; dirtyOnCrash: boolean | null; readOnly?: boolean | null; warning?: string | null }
export type SearchMatch = { text: string; index: number; lineNumber: number }
export type SheetCell = { rawValue: string; displayValue: string; formula: string | null; style: CellStyle | null }
export type SheetData = { id: string; name: string; cells: { [key in string]: SheetCell }; colWidths: { [key in number]: number }; rowHeights: { [key in number]: number }; freezeRows: number; freezeCols: number; charts?: ChartModel[]; filterQuery?: string | null; merges?: MergeRange[]; autoFilter?: AutoFilterState | null; conditionalFormatting?: ConditionalFormattingRule[]; pivotTables?: PivotTableModel[]; tables?: TableModel[] }
export type Slide = { id: string; layout: string; elements: SlideElement[]; notes: string; bgOverride: string | null;
/**
 * Per-slide transition: "none" | "fade" | "slide-left" | "slide-right"
 */
transition?: string }
export type SlideElement = { id: string; x: number; y: number; width: number; height: number; rotation: number; zIndex: number;
/**
 * Per-element entrance animation: "none" | "fade"
 */
entrance?: string; kind: ElementKind }
export type SlideTheme = { id: string; name: string; bgColor: string; textColor: string; accentColor: string; fontFamily: string }
export type TableModel = { id: string; name: string; range: CellRange; columns?: string[]; style?: string | null; showHeaderRow?: boolean; showTotalRow?: boolean }
export type WorkbookModel = { sheets: SheetData[]; activeSheetIndex: number; namedRanges?: NamedRange[] }
export type XlsxImportResponse = { workbook: WorkbookModel; warnings: string[] }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
